AWSTemplateFormatVersion: "2010-09-09"
Description: This CFN Template launches an EC2 instance, an autoscaling group,and an application load balancer. Created by Group 4

Parameters:
  
  InstanceAmiId:
    Type: String
    Description: The AMI ID to use in launching the EC2 instance.
    Default: "ami-03a6eaae9938c858c"
  
  VPC:
    Type: String
    Description: A virtual private cloud
    Default: "vpc-00f9c4d2d7ac05ec4"
   
  PrivateSubnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: The Subnets to launch the EC2 instance into. Also implies the VPC (It is deployed into private subnet(s)).

  PublicSubnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: The Subnets to launch the Load Balancer instance into. Also implies the VPC (It is deployed into public subnet(s)).
    
  Region:
    Type: String
    Description: The region to deploy the EC2 instance in.
    Default: us-east-1
   
  
  # CodeDeployTag:
  #   Type: String
  #   Description: The tag to attach to the EC2 instance to enable targeting by CodeDeploy Agent.
  #   Default: ""

# Conditions:
#     CodeDeployTagParamterIsAvailable: !Not [!Equals [!Ref CodeDeployTag, ""]]


Resources: 
  ELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ELB Security Group
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Security Group
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        SourceSecurityGroupId:
          Fn::GetAtt:
          - ELBSecurityGroup
          - GroupId


  EC2TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTPS
      HealthCheckTimeoutSeconds: 15
      HealthyThresholdCount: 5
      Matcher:
        HttpCode: '200'
      Name: EC2TargetGroup
      Port: 443
      Protocol: HTTPS
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: '20'
      UnhealthyThresholdCount: 3
      VpcId: !Ref VPC

  ELBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref EC2TargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets: !Ref PublicSubnets

  MyIPSetDenylist: 
    Type: AWS::WAF::IPSet
    Properties: 
      Name: IPSet to deny listed IP addresses
      IPSetDescriptors: 
        - 
          Type: IPV4
          Value: 192.0.2.44/32
        - 
          Type: IPV4
          Value: 192.0.7.0/24

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-launch-template
      LaunchTemplateData:
        ImageId: !Ref InstanceAmiId
        InstanceType: t2.micro

        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            echo "[B3C3 INFO] ###Beginning of B3C3 User Data Script"
            echo "[B3C3 INFO] Installing Java on the Instance"
            dnf install -y java
            echo "[B3C3 INFO] Installing ruby and wget"
            dnf install -y ruby wget
            echo "[B3C3 INFO] Using wget to download Code Deploy Agent Install Script"
            wget -O /tmp/cdagent_install https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
            echo "[B3C3 INFO] Making the Code Deploy Agent Install Script Executable"
            chmod +x /tmp/cdagent_install
            echo "[B3C3 INFO] Installing and Starting the Amazon Code Deploy Agent using the Install Script"
            /tmp/cdagent_install auto
            echo "[B3C3 INFO] Checking the status of Code Deploy Agent via systemctl"
            systemctl status codedeploy-agent
            echo "[B3C3 INFO] End of B3C3 User Data Script###"
 
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MaxSize: '5'
      MinSize: '2'
      DesiredCapacity: '2'
      TargetGroupARNs: 
        - !Ref EC2TargetGroup
      VPCZoneIdentifier: !Ref PrivateSubnets

# Outputs:
#   EC2InstanceId:
#     Value: !Ref EC2Instance

#   EC2CodeDeployTag:
#     Value: !If [CodeDeployTagParamterIsAvailable, !Ref CodeDeployTag, !Ref AWS::StackName]

# End of CFN Template